# Generated by Django 4.0.6 on 2022-08-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='price',
            field=models.TextField(blank=True),
        ),
    ]
