# Generated by Django 4.1 on 2022-08-04 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Price', '0003_alter_data_date_alter_data_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='ticker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chi', to='Price.ticker'),
            preserve_default=False,
        ),
    ]
