# Generated by Django 4.1 on 2022-08-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Price', '0004_ticker_alter_data_price_data_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='ticker',
        ),
        migrations.AddField(
            model_name='data',
            name='tick',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
