# Generated by Django 4.1 on 2022-08-05 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Price', '0005_remove_data_ticker_data_tick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='tick',
        ),
        migrations.AddField(
            model_name='data',
            name='ticker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickerr', to='Price.ticker'),
            preserve_default=False,
        ),
    ]
