# Generated by Django 4.1 on 2022-08-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Price', '0006_remove_data_tick_data_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='ticker',
            field=models.CharField(max_length=50),
        ),
    ]
