# Generated by Django 4.1 on 2022-08-05 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Price', '0007_alter_data_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company', to='Price.ticker'),
        ),
    ]
